#!/usr/bin/env bash
set -euo pipefail

# Get script directory and extension root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
HOST_DIR="$SCRIPT_DIR"
# Find GitHub directory (serverless-llm sibling)
GITHUB_DIR="$(cd "$SCRIPT_DIR" && while [[ "$PWD" != "/" ]]; do if [[ -d "$PWD/../serverless-llm" ]]; then cd ..; pwd; exit 0; fi; cd ..; done; echo "")"
ROOT_DIR="${GITHUB_DIR:-$(cd "$EXT_DIR/../.." && pwd)}"

# Read config from .shipctl.env if it exists
read_env_config() {
  local env_file="$EXT_DIR/.shipctl.env"
  if [[ -f "$env_file" ]]; then
    while IFS='=' read -r key value; do
      # Skip comments and empty lines
      [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
      # Trim whitespace
      key=$(echo "$key" | xargs)
      value=$(echo "$value" | xargs)
      case "$key" in
        PYTHON_PATH) export CONFIG_PYTHON_PATH="$value" ;;
        REPO_PATH) export CONFIG_REPO_PATH="$value" ;;
      esac
    done < "$env_file"
  fi
}

read_env_config

# Read extension ID from .extension-id file if not provided
if [[ $# -eq 0 ]]; then
  if [[ -f "$EXT_DIR/.extension-id" ]]; then
    EXT_ID="$(cat "$EXT_DIR/.extension-id" | tr -d '[:space:]')"
    echo "Using extension ID from .extension-id: $EXT_ID"
  else
    echo "Usage: $0 [extension-id] [browser]"
    echo ""
    echo "No extension ID provided and .extension-id file not found."
    echo "Run 'make build' first to generate the extension with stable ID."
    exit 1
  fi
else
  EXT_ID="$1"
fi

BROWSER="${2:-chrome}"

PY="$HOST_DIR/serverless_llm_native_host.py"

pick_python() {
  # Try config file first
  if [[ -n "${CONFIG_PYTHON_PATH:-}" && -x "$CONFIG_PYTHON_PATH" ]]; then
    echo "$CONFIG_PYTHON_PATH"
    return
  fi
  # Try serverless-llm venv (sibling directory)
  if [[ -x "$ROOT_DIR/serverless-llm/venv/bin/python" ]]; then
    echo "$ROOT_DIR/serverless-llm/venv/bin/python"
    return
  fi
  # Try system python3
  if command -v python3 >/dev/null 2>&1; then
    command -v python3
    return
  fi
  # Try system python
  if command -v python >/dev/null 2>&1; then
    command -v python
    return
  fi
  echo "Python not found. Install Python 3.11+ or set PYTHON_PATH in .shipctl.env" >&2
  exit 1
}

PYTHON_BIN="$(pick_python)"

# Update shebang in Python file directly
sed -i.bak "1s|.*|#!$PYTHON_BIN|" "$PY"
rm -f "$PY.bak"
chmod +x "$PY"

# Create config file in native-host directory
# Use REPO_PATH from existing config or try to find serverless-llm sibling
REPO_PATH="${CONFIG_REPO_PATH:-}"
if [[ -z "$REPO_PATH" && -d "$ROOT_DIR/serverless-llm" ]]; then
  REPO_PATH="$ROOT_DIR/serverless-llm"
fi

cat > "$HOST_DIR/.shipctl.env" <<EOF
# shipctl configuration
# Auto-generated by install script

# Path to Python interpreter (for native host)
PYTHON_PATH=${CONFIG_PYTHON_PATH:-}

# Path to serverless-llm repository (for backend operations)
REPO_PATH=$REPO_PATH

# Path to extension source directory
EXTENSION_DIR=$EXT_DIR
EOF

pick_dest_dir() {
  case "$BROWSER" in
    chrome)
      echo "$HOME/.config/google-chrome/NativeMessagingHosts"
      ;;
    chromium)
      echo "$HOME/.config/chromium/NativeMessagingHosts"
      ;;
    brave)
      echo "$HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts"
      ;;
    *)
      echo "Unknown browser: $BROWSER" >&2
      echo "Options: chrome | chromium | brave" >&2
      exit 1
      ;;
  esac
}

DEST_DIR="$(pick_dest_dir)"
mkdir -p "$DEST_DIR"

MANIFEST_PATH="$DEST_DIR/io.neevs.serverless_llm.json"
cat > "$MANIFEST_PATH" <<EOF
{
  "name": "io.neevs.serverless_llm",
  "description": "Serverless LLM native host (start/stop local backend)",
  "path": "$PY",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
EOF

echo ""
echo "✓ Installed native host for $BROWSER"
echo "  Manifest: $MANIFEST_PATH"
echo "  Extension ID: $EXT_ID"
echo ""
echo "Next steps:"
echo "  1) Reload the extension"
echo "  2) Open the side panel and use Backend controls"
